Adding capability to skip if not needed

diff --git a/roles/edb_efminstall/tasks/C07-RH07-EFM-configure.yml b/roles/edb_efminstall/tasks/C07-RH07-EFM-configure.yml
--- a/roles/edb_efminstall/tasks/C07-RH07-EFM-configure.yml
+++ b/roles/edb_efminstall/tasks/C07-RH07-EFM-configure.yml
@@ -1,66 +1,82 @@
 ---
+- name: Check if we have efm.properties file or not
+  stat:
+    path: "{{ EFM_PROPERTIES }}"
+  become: yes
+  register: stat_efm_properties
+
+- name: Check if we have efm.nodes file or not
+  stat:
+    path: "{{ EFM_PROPERTIES }}"
+  become: yes
+  register: stat_efm_nodes
 
 - name: Create EFM properties File
   copy:
-    src: /etc/edb/efm-{{ EFM_VERSION }}/efm.properties.in
-    dest: /etc/edb/efm-{{ EFM_VERSION }}/efm.properties
+    src: "{{ EFM_PROPERTIES }}.in"
+    dest: "{{ EFM_PROPERTIES }}"
     owner: "{{ PG_EFM_USER }}"
     group: "{{ PG_EFM_USER }}"
     remote_src: yes
+  when: not stat_efm_properties.stat.exists
   become: yes
 
 - name: Create EFM nodes File
   copy:
-    src: /etc/edb/efm-{{ EFM_VERSION }}/efm.nodes.in
-    dest: /etc/edb/efm-{{ EFM_VERSION }}/efm.nodes
+    src: "{{ EFM_NODE_FILE }}.in"
+    dest: "{{ EFM_NODE_FILE }}"
     owner: "{{ PG_EFM_USER }}"
     group: "{{ PG_EFM_USER }}"
     remote_src: yes
+  when: not stat_efm_nodes.stat.exists
+  become: yes
+
+- name: Update private IPs in efm.nodes file
+  shell: |
+    set -o pipefail
+    set -eu
+    EFM_NODE_FILE="{{ EFM_NODE_FILE }}"
+    NEED_UPDATE=1
+    for node in {{ EFM_NODES_LIST }}
+    do
+       CHECK=$(grep -q "${node}" ${EFM_NODE_FILE} && echo "found" \
+                      || echo "not_found" )
+       [[ "${CHECK}" = "not_found" ]] && NEED_UPDATE=0  || NEED_UPDATE=1
+    done
+    if [[ ${NEED_UPDATE} -eq 0 ]]
+    then
+       echo "{{ EFM_NODES_LIST }}" > ${EFM_NODE_FILE}
+       echo "node_updated"
+    fi
+  args:
+    executable: /bin/bash
+  register: output
+  changed_when: "'node_updated' in output.stdout"
   become: yes
 
 - name: Generate EFM encrypted Password
   shell: |
-   /usr/edb/efm-{{ EFM_VERSION }}/bin/efm encrypt efm --from-env
-   touch /etc/edb/efm-{{ EFM_VERSION }}/.efmpass
+   {{ EFM_BIN_PATH }}/efm encrypt efm --from-env
   args:
-    creates: "/etc/edb/efm-{{ EFM_VERSION }}/.efmpass"
     executable: /bin/bash
   environment:
     EFMPASS: "{{ PG_EFM_USER_PASSWORD }}"
   register: pass_opt
+  changed_when: pass_opt.rc == 0
+  become: yes
+  failed_when: "'EFMPASS password not found.' in pass_opt.stdout"
 
 - name: Update EFM efm.properties File
   lineinfile:
     path: /etc/edb/efm-{{ EFM_VERSION }}/efm.properties
     regexp: "{{ line_item.name + '=' }}"
     line: "{{ line_item.name + '=' + line_item.value|string }}"
-  with_items:
-        - { name: db.user, value: "{{ PG_EFM_USER }}"}
-        - { name: db.password.encrypted, value: "{{ pass_opt.stdout }}"}
-        - { name: db.port, value: "{{ PG_PORT }}"}
-        - { name: db.database, value: "{{ PG_EFM_DATABASE }}"}
-        - { name: db.service.owner, value: "{{ PG_OWNER }}"}
-        - { name: db.service.name, value: "{{ PG_SERVICE }}"}
-        - { name: db.bin, value: "{{ PG_BIN_PATH }}"}
-        - { name: db.recovery.dir, value: "{{ PG_DATA }}"}
-        - { name: db.data.dir, value: "{{ PG_DATA }}"}
-        - { name: user.email, value: "{{ EFM_NOTIFICATION_EMAIL }}"}
-        - { name: auto.allow.hosts, value: true}
-        - { name: stable.nodes.file, value: true}
-        - { name: bind.address, value: "{{ item.value.private_ip }}:7800"}
-        - { name: is.witness, value: "{{ EFM_WITNESS }}" }
-        - { name: application.name, value: "{{ item.key }}" }
-        - { name: update.physical.slots.period, value: "10" }
+    state: present
+  with_items: "{{ EFM_PARAMETERS }}"
   loop_control:
-    loop_var: line_item
+   loop_var: line_item
   become: yes
-
-- name: Update private IPs in efm.nodes file
-  blockinfile:
-    path: /etc/edb/efm-{{ EFM_VERSION }}/efm.nodes
-    block: |
-        {{ EFM_NODES_LIST }}
-  become: yes
+  notify: Restart the EFM Service
 
 - name: Start EFM service
   systemd:
@@ -73,12 +89,19 @@
   shell: |
     set -o pipefail
     set -eu
+    CLUSTER_STATUS="$( {{ EFM_BIN_PATH }}/efm cluster-status-json efm |jq '.allowednodes'"
     for ip_address in {{ ALL_NODE_IPS|join(' ') }}
     do
-      /usr/edb/efm-{{ EFM_VERSION }}/bin/efm allow-node efm ${ip_address}
+       CHECK=$( echo "${CLUSTER_STATUS}"|grep ${ip_address}|wc -l )
+       if [[ ${CHECK} -eq 0 ]]
+       then
+          {{ EFM_BIN_PATH }}/efm allow-node efm ${ip_address} && echo "successful" \
+            || echo "Failed allow-node"
+       fi
     done
-    rm -f /etc/edb/efm-{{ EFM_VERSION }}/.allowed
   args:
-    creates: "/etc/edb/efm-{{ EFM_VERSION }}/.allowed"
     executable: /bin/bash
   register: output
+  changed_when: "'successful' in output.stdout"
+  failed_when: "'Failed allow-node' in output.stdout"
+  become: yes
